name: "Push container to registry"

on:
  pull_request:
    paths:
      - Dockerfile
  push:
    tags:
      - "v*.*.*"

jobs:
  swift-package-push:
    runs-on: local
    steps:
      - name: Checkout
        uses: https://codeberg.org/Cyberbeni/actions-checkout@v1
      - name: Push container to registry
        shell: bash
        env:
          IMAGES: "codeberg.org/cyberbeni/index.htmx,docker.io/cyberbeni/index.htmx"
          # Login
          PACKAGE_REGISTRY_ACCESS_TOKEN: "${{ secrets.PACKAGE_REGISTRY_ACCESS_TOKEN }}"
          DOCKERHUB_USER: "${{ vars.DOCKERHUB_USER }}"
          DOCKERHUB_PASSWORD: "${{ secrets.DOCKERHUB_PASSWORD }}"
        run: |
          "$CI_SCRIPTS/docker/push.sh"
