name: "PR Checks"

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  swift-pr-checks:
    runs-on: local
    steps:
      - name: Checkout
        uses: https://codeberg.org/Cyberbeni/actions-checkout@v1
      - name: PR Checks
        shell: bash
        run: |
          "$CI_SCRIPTS/swift/pr-checks.sh"
