variables:
  - &IMAGE_NAME "docker.io/cyberbeni/index.htmx"

labels:
  backend: local

when:
  - event: pull_request
    path: Dockerfile
  - event: tag
    ref: refs/tags/v*.*.*

steps:
  - name: Update CI scripts
    image: bash
    commands: |
      [ -d /home/ci/ci-runner/scripts ] || git clone https://codeberg.org/Cyberbeni/ci-scripts /home/ci/ci-runner/scripts
      git -C /home/ci/ci-runner/scripts fetch
      git -C /home/ci/ci-runner/scripts checkout master
      git -C /home/ci/ci-runner/scripts merge --ff-only
  - name: Calculate tags
    image: bash
    commands: |
      /home/ci/ci-runner/scripts/docker/calculate-tags.sh
  - name: Build and push Docker image
    image: plugin-docker-buildx
    settings:
      logins:
        - registry: docker.io
          username:
            from_secret: DOCKERHUB_USER
          password:
            from_secret: DOCKERHUB_PASSWORD
      repo: *IMAGE_NAME
      platforms: linux/amd64,linux/arm64
      no_cache: true
