labels:
  backend: local

when:
  - event: pull_request
  - event: push
    branch: ${CI_REPO_DEFAULT_BRANCH}

steps:
  - name: Update CI scripts
    image: bash
    commands: |
      [ -d /home/ci/ci-runner/scripts ] || git clone https://codeberg.org/Cyberbeni/ci-scripts /home/ci/ci-runner/scripts
      git -C /home/ci/ci-runner/scripts fetch
      git -C /home/ci/ci-runner/scripts checkout master
      git -C /home/ci/ci-runner/scripts merge --ff-only
  - name: PR checks
    image: bash
    commands: |
      /home/ci/ci-runner/scripts/swift/pr-checks.sh
