name: PR checks

on:
  pull_request:
  push:
    branches: master

jobs:
  swiftformat-lint:
    uses: Cyberbeni/workflows/.github/workflows/swiftformat-lint.yml@master
  swift-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install xcbeautify
      uses: Cyberbeni/install-swift-tool@v3
      with:
        url: https://github.com/cpisciotta/xcbeautify
        version: '*'
    - name: Test
      shell: bash
      run: |
        set -o pipefail
        swift test | xcbeautify
  check-codegen:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Run Codegen
      run: |
        ./scripts/codegen.sh
    - name: Ensure unchanged
      run: |
        git status
        [[ -z $(git status --porcelain) ]] || exit 1
